apiVersion: apps/v1
kind: Deployment
metadata:
  name: annms-dbms-{{ .Values.env }}
  namespace: annms-{{ .Values.env }}
  labels:
    app: annms-dbms-{{ .Values.env }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: annms-dbms-{{ .Values.env }}
  template:
    metadata:
      labels:
        app: annms-dbms-{{ .Values.env }}
    spec:
      containers:
      - name: annms-dbms-{{ .Values.env }}
        image: {{ .Values.mysqlServer.image }}
        {{- if .Values.mysqlServer.envValues }}
        env:
        {{- range $key, $value := .Values.mysqlServer.envValues }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: 3306
        volumeMounts:
          - name: mysql-abbns-user-scripts
            mountPath: /docker-entrypoint-initdb.d/abbns-user-scripts.sql
            subPath: abbns-user-scripts.sql
      volumes:
      - name: mysql-abbns-user-scripts
        configMap:
          name: abbns-user-scripts
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: abbns-user-scripts
data:
  abbns-user-scripts.sql: |-
    {{ .Values.mysqlServer.createUsers }}
---
apiVersion: v1
kind: Service
metadata:
  name: annms-dbms-{{ .Values.env }}-svc
  namespace: annms-{{ .Values.env }}
spec:
  type: ClusterIP
  ports:
  - port: 3306
  selector:
    app: annms-dbms-{{ .Values.env }}